### ISSUE TITLE
SCSS file can't use for Production

### ISSUE THREAD

**Issue by Aofhero** [liuy97/angular2-material-seed#1]
Hi i'm try build.prod

But my SCSS file added in folder css  can't use on Prod.  **_In dev mode no problem_**

app
 -->css
        
-   main.css
-   custommaterial.scss (new file)
-   myCss.scss  (new file)

My project.config.ts

    this.APP_ASSETS = [
        {src: `${this.CSS_SRC}/myCss.css`, inject: true, vendor: false},
        {src: `${this.CSS_SRC}/custommaterial.css`, inject: true, vendor: false}
    ];

Tell me about how to config when add new scss file.

Thanks for good seed project.

**Comment by liuy97** [comment]
I will look into it.

**Comment by liuy97** [comment]
Hi,
I have tested scss. The scss and css files cannot be mixed in this project. So you have to rename *.css to *.scss. The scss folder has to be created. The example is showed in the image.
![screen shot 2017-05-24 at 12 27 39 pm](https://cloud.githubusercontent.com/assets/2961144/26399281/b1130356-407c-11e7-8076-4aae05abc7ec.png)
```
@Component({
  moduleId: module.id,
  selector: 'sd-app',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
})
```
variable.scss
```
$color: red;
```

```bash
ENABLE_SCSS=1 npm start
ENABLE_SCSS=1 npm run build.prod
```

**Comment by kunalkamble** [comment]
Thank you so much @liuy97, 
I also had to change ***.css** to ***.scss inside** `/tools/tasks/seed/build.html_css.ts`.

![screen shot 2019-01-18 at 8 52 06 am](https://user-images.githubusercontent.com/1706750/51390834-66c96200-1afe-11e9-82ab-ffe452f29b30.png)
