### ISSUE TITLE
Problem catch up event scrolling

### ISSUE THREAD

**Issue by Aofhero** [liuy97/angular2-material-seed#2]
Hi I'm Shirley

I use this project but I have problem to catch event scrolling

Please Help me to do this.

I try @HostListener('window:scroll', ['$event'])   <   Not Work
And
`window.addEventListener('scroll', function(){
        let number = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0;
       console.log(number);
}, true);`  

I got 0 any time

**Comment by liuy97** [comment]
It's not a problem fromthis project.
I used the following code, and it works.

```
@HostListener("window:scroll", [])
  onWindowScroll() {
    const number = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0;
    console.log(number);
  }
```
https://plnkr.co/edit/niNinJr5loAcYmFugzhe?p=preview
