### ISSUE TITLE
Uncaught Error: StaticInjectorError(Platform: core)[zn]:    NullInjectorError: No provider for zn!

### ISSUE THREAD

**Issue by sharmaprashant232** [liuy97/angular2-material-seed#5]
Hi. I have made build successfully using npm run build.prod.rollup.aot.
After build when I start webapp, it gives me error related to providers that I am not understanding.

Uncaught Error: StaticInjectorError(Platform: core)[zn]: 
  NullInjectorError: No provider for zn!
    at t.get (app.js?1526539700791:1)
    at app.js?1526539700791:1
    at Ge (app.js?1526539700791:1)
    at t.get (app.js?1526539700791:1)
    at t.bootstrapModule (app.js?1526539700791:1)
    at app.js?1526539700791:1
    at app.js?1526539700791:1

Help me with this issue. Thanks

**Comment by liuy97** [comment]
The error message shows you have to provide zn, which is injected.

**Comment by sharmaprashant232** [comment]
I didn't see anything related to zn. I haven't created any variabled zn so where to find it?

**Comment by liuy97** [comment]
Did you write your own codes, or you run the sample without changes?

**Comment by sharmaprashant232** [comment]
I run the sample without changes.
Here is the error where i got in appjs
 function Se(t) {
        return "function" == typeof t && t.hasOwnProperty("__forward_ref__") && t.__forward_ref__ === ke ? t() : t
    }
    var Oe = "__source"
      , Ee = new Object
      , Pe = Ee
      , Ae = function() {
        function t() {}
        return t.prototype.get = function(t, e) {
            if (void 0 === e && (e = Ee),
            e === Ee)
                throw new Error("NullInjectorError: No provider for " + Ce(t) + "!");    ////////error got here
            return e
        }
        ,
        t
    }()
      , De = function() {
        function t() {}
        return t.create = function(t, e) {
            return Array.isArray(t) ? new Be(t,e) : new Be(t.providers,t.parent,t.name || null)
        }
        ,
        t.THROW_IF_NOT_FOUND = Ee,
        t.NULL = new Ae,
        t
    }()
      , Ie = function(t) {
        return t
    }
      , Te = []
      , Re = Ie
      , Le = function() {
        return Array.prototype.slice.call(arguments)
    }
      , Me = {}
      , je = function(t) {
        for (var e in t)
            if (t[e] === Me)
                return e;
        throw Error("!prop")
    }({
        provide: String,
        useValue: Me
    })
      , Fe = "ngTempTokenPath"
      , Ne = De.NULL
      , Ve = /\n/gm
      , ze = "ɵ"
      , Be = function() {
        function t(t, e, n) {
            void 0 === e && (e = Ne),
            void 0 === n && (n = null),
            this.parent = e,
            this.source = n;
            var i = this._records = new Map;
            i.set(De, {
                token: De,
                fn: Ie,
                deps: Te,
                value: this,
                useNew: !1
            }),
            function t(e, n) {
                if (n)
                    if ((n = Se(n))instanceof Array)
                        for (var i = 0; i < n.length; i++)
                            t(e, n[i]);
                    else {
                        if ("function" == typeof n)
                            throw Ue("Function/Class not supported", n);
                        if (!n || "object" != typeof n || !n.provide)
                            throw Ue("Unexpected provider", n);
                        var r = Se(n.provide)
                          , o = function(t) {
                            var e = function(t) {
                                var e = Te
                                  , n = t.deps;
                                if (n && n.length) {
                                    e = [];
                                    for (var i = 0; i < n.length; i++) {
                                        var r = 6
                                          , o = Se(n[i]);
                                        if (o instanceof Array)
                                            for (var a = 0, s = o; a < s.length; a++) {
                                                var l = s[a];
                                                l instanceof ce || l == ce ? r |= 1 : l instanceof he || l == he ? r &= -3 : l instanceof pe || l == pe ? r &= -5 : o = l instanceof le ? l.token : Se(l)
                                            }
                                        e.push({
                                            token: o,
                                            options: r
                                        })
                                    }
                                } else if (t.useExisting) {
                                    var o = Se(t.useExisting);
                                    e = [{
                                        token: o,
                                        options: 6
                                    }]
                                } else if (!(n || je in t))
                                    throw Ue("'deps' required", t);
                                return e
                            }(t)
                              , n = Ie
                              , i = Te
                              , r = !1
                              , o = Se(t.provide);
                            if (je in t)
                                i = t.useValue;
                            else if (t.useFactory)
                                n = t.useFactory;
                            else if (t.useExisting)
                                ;
                            else if (t.useClass)
                                r = !0,
                                n = Se(t.useClass);
                            else {
                                if ("function" != typeof o)
                                    throw Ue("StaticProvider does not have [useValue|useFactory|useExisting|useClass] or [provide] is not newable", t);
                                r = !0,
                                n = o
                            }
                            return {
                                deps: e,
                                fn: n,
                                useNew: r,
                                value: i
                            }
                        }(n);
                        if (!0 === n.multi) {
                            var a = e.get(r);
                            if (a) {
                                if (a.fn !== Le)
                                    throw He(r)
                            } else
                                e.set(r, a = {
                                    token: n.provide,
                                    deps: [],
                                    useNew: !1,
                                    fn: Le,
                                    value: Te
                                });
                            r = n,
                            a.deps.push({
                                token: r,
                                options: 6
                            })
                        }
                        var s = e.get(r);
                        if (s && s.fn == Le)
                            throw He(r);
                        e.set(r, o)
                    }
            }(i, t)
        }
        return t.prototype.get = function(e, t) {
            var n = this._records.get(e);
            try {
                return Ge(e, n, this._records, this.parent, t)
            } catch (t) {
                var i = t[Fe];
                throw e[Oe] && i.unshift(e[Oe]),
                t.message = We("\n" + t.message, i, this.source),
                t.ngTokenPath = i,
                t[Fe] = null,
                t
            }
        }
        ,

**Comment by sharmaprashant232** [comment]
and 
 t.prototype.bootstrapModule = function(t, e) {
            var n = this;
            void 0 === e && (e = []);
            var i = this.injector.get(zn)    ///////////////////////////////// error
              , r = xi({}, e);
            return i.createCompiler([r]).compileModuleAsync(t).then(function(t) {
                return n.bootstrapModuleFactory(t, r)
            })
        }
        ,

**Comment by liuy97** [comment]
OK, I will investigate it.

**Comment by liuy97** [comment]
I run build.prod.rollup.aot and put it into apache2 server. I did not get this error.

**Comment by sharmaprashant232** [comment]
Ok. I will investigate it.

**Comment by sharmaprashant232** [comment]
Hi. I tried cleanup my project and put only one component. still getting this error. This is so weird.

**Comment by sharmaprashant232** [comment]
[https://gitlab.com/vfirstt-nexttrophy/nexttrophy-webapp1](url)

**Comment by liuy97** [comment]
This demo does not use zn as a provider at all. Maybe you try angular 6 from my latest commit.

**Comment by sharmaprashant232** [comment]
[nexttrophy-webapp1-master.zip](https://github.com/liuy97/angular2-material-seed/files/2022549/nexttrophy-webapp1-master.zip)

**Comment by sharmaprashant232** [comment]
Can you please check this? I have attached my file. This is from angular 5+ material 5 seed project.

**Comment by liuy97** [comment]
I confirm your code works as expected. "Hello this is test page" is showed after loading. I use MacOS. Maybe you can remove package-lock.json and node_modules and try to run "npm i" again.

**Comment by sharmaprashant232** [comment]
OK. Can you please check with this link? http://env-9179659-nexttrophy-webpack.ind-cloud.everdata.com/
I am using jenkins to make build and using command for build npm install  && npm run build.prod.rollup.aot

**Comment by liuy97** [comment]
It's difficult to debug it in your environment. But try to confirm whether your binary package works fine in a apache server.

**Comment by sharmaprashant232** [comment]
I ran it in apache server. It gives me error.

Uncaught Error: StaticInjectorError(Platform: core)[CompilerFactory]: 
  NullInjectorError: No provider for CompilerFactory!
    at _NullInjector.get (app.js?1526908368526:1895)
    at resolveToken (app.js?1526908368526:2089)
    at tryResolveToken (app.js?1526908368526:2048)
    at StaticInjector.get (app.js?1526908368526:1951)
    at PlatformRef.bootstrapModule (app.js?1526908368526:3620)
    at app.js?1526908368526:48507
    at app.js?1526908368526:48508

I think this is because of:
I have changed main-prod.ts file.
import { enableProdMode } from '@angular/core';
import { platformBrowser } from '@angular/platform-browser';

// import { AppModuleNgFactory } from './app.module.ngfactory';
import { AppModule } from './app.module';

enableProdMode();

// platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
platformBrowser().bootstrapModuleFactory(<any>AppModule/*, options*/);

Because it didn't find app.module.ngfactory

Is this the issue?

**Comment by sharmaprashant232** [comment]
This is the code. Sorry for above
import { enableProdMode } from '@angular/core';
import { platformBrowser } from '@angular/platform-browser';

// import { AppModuleNgFactory } from './app.module.ngfactory';
import { AppModule } from './app.module';

enableProdMode();

// platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
platformBrowser().bootstrapModule(AppModule/*, options*/);

**Comment by liuy97** [comment]
No, You cannot remove that line. That file is generated in compiling time.

**Comment by sharmaprashant232** [comment]
So what I have to do now? 
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory); What should I give here?

**Comment by liuy97** [comment]
I suggest not to modify that file if you not sure what you did. I believe this issue is not related to this project. You can access demo via http://liuy97.github.io/angular2-material-seed. You can try to put https://github.com/liuy97/angular2-material-seed/tree/gh-pages into your apache. If it works fine, you can build it and copy **dist/prod** folder to apache server after you run **npm run build.prod.rollup.aot** . Step by step, you will figure it out.

**Comment by sharmaprashant232** [comment]
Hey, thanks man. Now it works fine. Thanks again.

**Comment by liuy97** [comment]
I am glad that you made it work.
