### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by sharmaprashant232** [liuy97/angular2-material-seed#6]
I am getting error while runnning command: npm run build.prod.rollup.aot
<--- Last few GCs --->

  136050 ms: Mark-sweep 1313.6 (1436.7) -> 1313.5 (1436.7) MB, 1772.7 / 0.0 ms [allocation failure] [GC in old space requested].
  137793 ms: Mark-sweep 1313.5 (1436.7) -> 1313.5 (1436.7) MB, 1743.1 / 0.0 ms [allocation failure] [GC in old space requested].
  139530 ms: Mark-sweep 1313.5 (1436.7) -> 1332.3 (1420.7) MB, 1736.1 / 0.0 ms [last resort gc].
  141264 ms: Mark-sweep 1332.3 (1420.7) -> 1351.1 (1420.7) MB, 1733.8 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000208255CF791 <JS Object>
    1: emitSourceFileOrBundle(aka emitSourceFileOrBundle) [D:\vfirstt_nexttrophy\nexttrophy-webapp\node_modules\typescript\lib\typescript.js:~66743] [pc=000003D999179463] (this=0000020825504381 <undefined>,_a=000001212F22C9D9 <an Object with map 00000058AFF438C1>,sourceFileOrBundle=00000140030B3229 <a SourceFileObject with map 0000013E4974CD41>)
    2: arguments adaptor frame: 3->2
    3: for...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Every time, it gives different output but with same result Javascript heap out of memory while starting in 
'build.js.prod.rollup.aot task.

Angular version:

`"
    "@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/flex-layout": "2.0.0-beta.9",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/material": "^2.0.0-beta.12",`
I tried using --max-old-space-size=N but no luck.

Can you please look into this issue?

**Comment by liuy97** [comment]
please check https://github.com/angular/angular-cli/issues/5618
suggest you to upgrade angular version

**Comment by sharmaprashant232** [comment]
As in this project, not using `@angular/cli.` Migrating from old to newer may be serious issue as it is already running in production. So is there a way to do this without migrating ?

**Comment by liuy97** [comment]
try 
`node --max_old_space_size=8192 .\node_modules\gulp\bin\gulp.js build.prod.rollup.aot --color --env-config prod --build-type prod`

All of your own code should be src/client/app, simple to copy that folder after you upgrade this seed.

**Comment by sharmaprashant232** [comment]
I will have to change get and post call as in angular 5 or 6 it uses, `@angular/comon/http` instead of `@angular/http` and related to token I will have to use TokenInterceptor.

**Comment by liuy97** [comment]
It's fine that the old version is enough for you. Major version of angular will always introduce breaking change.

**Comment by sharmaprashant232** [comment]
node --max_old_space_size=8192 .\node_modules\gulp\bin\gulp.js build.prod.rollup.aot --color --env-config prod --build-type prod is working fine. I can now make build properly although it increases my app.js size but it is very faster from the old ones. 
Is there any way to remove --max_old_space_size and do it programatically?

BTW thanks.

**Comment by liuy97** [comment]
It's a bug of Node you're using. Maybe A solution is to upgrade Node.js. Otherwise, you can create a shell script for this command.

**Comment by sharmaprashant232** [comment]
I am using node 6.14.2 and npm 6.0.1

**Comment by liuy97** [comment]
I use Node 8.9.
