### ISSUE TITLE
How to use SCSS?

### ISSUE THREAD

**Issue by kunalkamble** [liuy97/angular2-material-seed#8]
**SCSS**: How to enable scss/sass support in this project, as it not using angular cli for build process.

**Comment by kunalkamble** [comment]
@liuy97 could you please help me on how to use SCSS with this project as it is using gulp for the build process.

**Comment by liuy97** [comment]
hi, SCSS is supported, see #1 . The new angular cli becomes stable and support material 2 directly. If it is possible, I suggest you to use angular cli to manage projects directly.

**Comment by kunalkamble** [comment]
Thank you so much @liuy97 for the prompt response, you can close this issue.
